services:
  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DATABASE: note_app
    ports:
      - 5432:5432
    networks:
      - application_network

  note_app:
    container_name: note_app
    restart: always
    depends_on:
      - postgres
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
    volumes:
      - ./:/home/node/app
    networks:
      - application_network

volumes:
  postgres_volume:
  redis_volume:

networks:
  application_network:
    driver: bridge