services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: note_app
    ports:
      - 5432:5432
    networks:
      - application_network

  note_app:
    container_name: note_app
    restart: always
    depends_on:
      - postgres
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    command: node ace migration:run --force
    volumes:
      - ./:/home/node/app
    networks:
      - application_network

volumes:
  postgres_volume:
  redis_volume:

networks:
  application_network:
    driver: bridge