services:
  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - application_network

  note_app:
    container_name: brightky/note_app:latest
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    networks:
      - application_network

volumes:
  postgres_volume:
  redis_volume:

networks:
  application_network:
    driver: bridge